name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Xcode build
      uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        project: SkyblockClient.xcodeproj
        scheme: SkyblockClient
        destination: platform=macOS
        action: build
        configuration: Release
#     - name: testing again lel
#       run: ls -aR ~/Library/Developer/Xcode/DerivedData
    - name: Move file
      run: mv ~/Library/Developer/Xcode/DerivedData/SkyblockClient-dfoefjrechzdxxfncrxldlqimiqx/Build/Products/Release/SkyblockClient.app/Contents/MacOS/SkyblockClient SkyblockClient.app
    - name: Upload files
      uses: actions/upload-artifact@v2.2.2
      with:
        name: compiled
        path: SkyblockClient.app
        if-no-files-found: error
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Xcode test
      uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        project: SkyblockClient.xcodeproj
        scheme: SkyblockClient
        destination: platform=macOS
        action: build
        
    
