name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Xcode build
      uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        project: SkyblockClient.xcodeproj
        scheme: SkyblockClient
        destination: platform=macOS
        action: build
    - name: testing again lel
      run: ls -aR .
#     - name: Upload files
#       uses: actions/upload-artifact@v2.2.2
#       with:
#         name: compiled
#         path: SkyblockClient/products
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Xcode test
      uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        project: SkyblockClient.xcodeproj
        scheme: SkyblockClient
        destination: platform=macOS
        action: build
        
    
